// <auto-generated />
using System;
using Feedback.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Feedback.Migrations
{
    [DbContext(typeof(FeedbackContext))]
    partial class FeedbackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Feedback.Models.Hotel_Rating", b =>
                {
                    b.Property<int>("rating_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rating_id"));

                    b.Property<decimal>("average")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("cleanliness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("facilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("hotel_id")
                        .HasColumnType("int");

                    b.Property<decimal>("hotel_service")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("keyword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rating_id");

                    b.ToTable("hrating");
                });

            modelBuilder.Entity("Feedback.Models.Rating", b =>
                {
                    b.Property<int>("rating_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rating_id"));

                    b.Property<string>("customer_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("package_id")
                        .HasColumnType("int");

                    b.Property<decimal>("rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("rating_id");

                    b.ToTable("rating");
                });
#pragma warning restore 612, 618
        }
    }
}
